name: Publish to Docker Hub
on:
  workflow_dispatch:
    inputs:
      nginxVersion:
        description: "Nginx version"
        required: true
      nginxIngressVersion:
        description: "Nginx Ingress version"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create Dockerfile
        run: envsubst < Dockerfile-tpl > Dockerfile
        env:
          NGINX_VERSION: "${{ github.event.inputs.nginxVersion }}"
          NGINX_INGRESS_VERSION: "${{ github.event.inputs.nginxIngressVersion }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pujianto/nginx-ingress-brotli:${{ github.event.inputs.nginxIngressVersion }}
          build-args:
            NGINX_INGRESS_VERSION=${{ github.event.inputs.nginxIngressVersion }}
            NGINX_VERSION=${{ github.event.inputs.nginxVersion }}
          context: .
